<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOjwskzt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOjwskzt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOjwskzt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOjwskzt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOjwskzt\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ojwskzt',
    'container.build_id' => 'b36625ce',
    'container.build_time' => 1612016816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOjwskzt');
