<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVodtTLu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVodtTLu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVodtTLu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVodtTLu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVodtTLu\App_KernelDevDebugContainer([
    'container.build_hash' => 'VodtTLu',
    'container.build_id' => 'eeb0f999',
    'container.build_time' => 1612379383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVodtTLu');
