<?php

namespace ContainerR0FQ35W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5iMJCpoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5iMJCpo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5iMJCpo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LocalizationController::createLocalization' => ['privates', '.service_locator.UiBth57', 'get_ServiceLocator_UiBth57Service', true],
            'App\\Controller\\LocalizationController::deleteLocalization' => ['privates', '.service_locator.UiBth57', 'get_ServiceLocator_UiBth57Service', true],
            'App\\Controller\\LocalizationController::getAllLocalizations' => ['privates', '.service_locator.GQy2.ne', 'get_ServiceLocator_GQy2_NeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\LocalizationController:createLocalization' => ['privates', '.service_locator.UiBth57', 'get_ServiceLocator_UiBth57Service', true],
            'App\\Controller\\LocalizationController:deleteLocalization' => ['privates', '.service_locator.UiBth57', 'get_ServiceLocator_UiBth57Service', true],
            'App\\Controller\\LocalizationController:getAllLocalizations' => ['privates', '.service_locator.GQy2.ne', 'get_ServiceLocator_GQy2_NeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\LocalizationController::createLocalization' => '?',
            'App\\Controller\\LocalizationController::deleteLocalization' => '?',
            'App\\Controller\\LocalizationController::getAllLocalizations' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\LocalizationController:createLocalization' => '?',
            'App\\Controller\\LocalizationController:deleteLocalization' => '?',
            'App\\Controller\\LocalizationController:getAllLocalizations' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
