<?php

namespace ContainerR0FQ35W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalizationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LocalizationController' shared autowired service.
     *
     * @return \App\Controller\LocalizationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LocalizationController.php';

        return $container->services['App\\Controller\\LocalizationController'] = new \App\Controller\LocalizationController();
    }
}
